start cmd /k "python ./backend/ms_reserva/main.py"
start cmd /k "python ./backend/ms_itinerarios/main.py"
start cmd /k "python ./backend/ms_pagamento/main.py"
start cmd /k "python ./backend/sistema_externo.py"
start cmd /k "python ./backend/ms_bilhete/bilhete.py"